[2023-02-05 21:11:27,553] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2023-02-05 21:11:27,562] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2023-02-05 21:11:27,562] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:11:27,563] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:11:27,563] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:11:27,581] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-05 00:00:00+00:00
[2023-02-05 21:11:27,585] {standard_task_runner.py:52} INFO - Started process 35036 to run task
[2023-02-05 21:11:27,590] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-05T00:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmpa9xgqa7r', '--error-file', '/tmp/tmpag_ol1ec']
[2023-02-05 21:11:27,591] {standard_task_runner.py:80} INFO - Job 139: Subtask task_2
[2023-02-05 21:11:27,664] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:11:27,743] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-05T00:00:00+00:00
[2023-02-05 21:11:27,745] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:11:27,746] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:11:27,754] {subprocess.py:85} INFO - Output:
[2023-02-05 21:11:27,755] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:11:27,756] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:11:27,756] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:11:27,768] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:11:27,771] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221105T000000, start_date=20230206T021127, end_date=20230206T021127
[2023-02-05 21:11:27,788] {standard_task_runner.py:92} ERROR - Failed to execute job 139 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35036)
[2023-02-05 21:11:27,801] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:11:27,845] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:14:18,650] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2023-02-05 21:14:18,663] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2023-02-05 21:14:18,664] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:14:18,664] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:14:18,664] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:14:18,685] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-05 00:00:00+00:00
[2023-02-05 21:14:18,689] {standard_task_runner.py:52} INFO - Started process 35233 to run task
[2023-02-05 21:14:18,695] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-05T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmppf6izqnm', '--error-file', '/tmp/tmpcrngvqrr']
[2023-02-05 21:14:18,696] {standard_task_runner.py:80} INFO - Job 133: Subtask task_2
[2023-02-05 21:14:18,803] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:14:18,907] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-05T00:00:00+00:00
[2023-02-05 21:14:18,909] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:14:18,910] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:14:18,919] {subprocess.py:85} INFO - Output:
[2023-02-05 21:14:18,920] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:14:18,920] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:14:18,920] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:14:18,935] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:14:18,942] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221105T000000, start_date=20230206T021418, end_date=20230206T021418
[2023-02-05 21:14:19,006] {standard_task_runner.py:92} ERROR - Failed to execute job 133 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35233)
[2023-02-05 21:14:19,026] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:14:19,080] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:33:22,604] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2023-02-05 21:33:22,615] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2023-02-05 21:33:22,616] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:33:22,616] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:33:22,616] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:33:22,636] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-05 00:00:00+00:00
[2023-02-05 21:33:22,639] {standard_task_runner.py:52} INFO - Started process 36097 to run task
[2023-02-05 21:33:22,644] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-05T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmphmqosbql', '--error-file', '/tmp/tmp4gosuq2u']
[2023-02-05 21:33:22,645] {standard_task_runner.py:80} INFO - Job 133: Subtask task_2
[2023-02-05 21:33:22,717] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-05T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:33:22,796] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-05T00:00:00+00:00
[2023-02-05 21:33:22,799] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:33:22,800] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:33:22,807] {subprocess.py:85} INFO - Output:
[2023-02-05 21:33:22,809] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:33:22,809] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:33:22,809] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:33:22,821] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:33:22,824] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221105T000000, start_date=20230206T023322, end_date=20230206T023322
[2023-02-05 21:33:22,840] {standard_task_runner.py:92} ERROR - Failed to execute job 133 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 36097)
[2023-02-05 21:33:22,856] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:33:22,898] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
