[2023-02-05 21:13:09,986] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2023-02-05 21:13:10,001] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2023-02-05 21:13:10,001] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:13:10,001] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:13:10,001] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:13:10,027] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-19 00:00:00+00:00
[2023-02-05 21:13:10,031] {standard_task_runner.py:52} INFO - Started process 35169 to run task
[2023-02-05 21:13:10,036] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-19T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmp420rsnla', '--error-file', '/tmp/tmp7c99e53p']
[2023-02-05 21:13:10,037] {standard_task_runner.py:80} INFO - Job 168: Subtask task_2
[2023-02-05 21:13:10,120] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-19T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:13:10,205] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-19T00:00:00+00:00
[2023-02-05 21:13:10,207] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:13:10,208] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:13:10,215] {subprocess.py:85} INFO - Output:
[2023-02-05 21:13:10,217] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:13:10,217] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:13:10,217] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:13:10,229] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:13:10,233] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221119T000000, start_date=20230206T021309, end_date=20230206T021310
[2023-02-05 21:13:10,249] {standard_task_runner.py:92} ERROR - Failed to execute job 168 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35169)
[2023-02-05 21:13:10,287] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:13:10,337] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:16:44,904] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2023-02-05 21:16:44,916] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2023-02-05 21:16:44,916] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:16:44,917] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:16:44,917] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:16:44,937] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-19 00:00:00+00:00
[2023-02-05 21:16:44,940] {standard_task_runner.py:52} INFO - Started process 35386 to run task
[2023-02-05 21:16:44,946] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-19T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmp936fr17b', '--error-file', '/tmp/tmp0cm8hfxm']
[2023-02-05 21:16:44,947] {standard_task_runner.py:80} INFO - Job 162: Subtask task_2
[2023-02-05 21:16:45,028] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-19T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:16:45,115] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-19T00:00:00+00:00
[2023-02-05 21:16:45,116] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:16:45,117] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:16:45,125] {subprocess.py:85} INFO - Output:
[2023-02-05 21:16:45,126] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:16:45,126] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:16:45,126] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:16:45,139] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:16:45,142] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221119T000000, start_date=20230206T021644, end_date=20230206T021645
[2023-02-05 21:16:45,158] {standard_task_runner.py:92} ERROR - Failed to execute job 162 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35386)
[2023-02-05 21:16:45,197] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:16:45,249] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
