[2023-02-05 21:12:59,730] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-17T00:00:00+00:00 [queued]>
[2023-02-05 21:12:59,740] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-17T00:00:00+00:00 [queued]>
[2023-02-05 21:12:59,740] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:12:59,740] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:12:59,740] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:12:59,773] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-17 00:00:00+00:00
[2023-02-05 21:12:59,776] {standard_task_runner.py:52} INFO - Started process 35152 to run task
[2023-02-05 21:12:59,781] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-17T00:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmpl209fybn', '--error-file', '/tmp/tmpf75gq15p']
[2023-02-05 21:12:59,783] {standard_task_runner.py:80} INFO - Job 165: Subtask task_2
[2023-02-05 21:12:59,859] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-17T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:12:59,940] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-17T00:00:00+00:00
[2023-02-05 21:12:59,942] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:12:59,942] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:12:59,950] {subprocess.py:85} INFO - Output:
[2023-02-05 21:12:59,951] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:12:59,952] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:12:59,952] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:12:59,963] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:12:59,967] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221117T000000, start_date=20230206T021259, end_date=20230206T021259
[2023-02-05 21:12:59,989] {standard_task_runner.py:92} ERROR - Failed to execute job 165 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35152)
[2023-02-05 21:13:00,033] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:13:00,078] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:16:29,361] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-17T00:00:00+00:00 [queued]>
[2023-02-05 21:16:29,373] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-17T00:00:00+00:00 [queued]>
[2023-02-05 21:16:29,373] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:16:29,373] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:16:29,373] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:16:29,395] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-17 00:00:00+00:00
[2023-02-05 21:16:29,398] {standard_task_runner.py:52} INFO - Started process 35370 to run task
[2023-02-05 21:16:29,403] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-17T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmp2ghjvojk', '--error-file', '/tmp/tmpvq40q6mz']
[2023-02-05 21:16:29,404] {standard_task_runner.py:80} INFO - Job 158: Subtask task_2
[2023-02-05 21:16:29,480] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-17T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:16:29,577] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-17T00:00:00+00:00
[2023-02-05 21:16:29,578] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:16:29,579] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:16:29,588] {subprocess.py:85} INFO - Output:
[2023-02-05 21:16:29,589] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:16:29,589] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:16:29,590] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:16:29,603] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:16:29,607] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221117T000000, start_date=20230206T021629, end_date=20230206T021629
[2023-02-05 21:16:29,625] {standard_task_runner.py:92} ERROR - Failed to execute job 158 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35370)
[2023-02-05 21:16:29,654] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:16:29,705] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
