[2023-02-05 21:12:21,304] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2023-02-05 21:12:21,315] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2023-02-05 21:12:21,315] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:12:21,315] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:12:21,315] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:12:21,338] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-12 00:00:00+00:00
[2023-02-05 21:12:21,341] {standard_task_runner.py:52} INFO - Started process 35103 to run task
[2023-02-05 21:12:21,347] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-12T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmpbnwcdwf0', '--error-file', '/tmp/tmphrjkk8vr']
[2023-02-05 21:12:21,348] {standard_task_runner.py:80} INFO - Job 155: Subtask task_2
[2023-02-05 21:12:21,430] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:12:21,518] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-12T00:00:00+00:00
[2023-02-05 21:12:21,520] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:12:21,527] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:12:21,536] {subprocess.py:85} INFO - Output:
[2023-02-05 21:12:21,538] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:12:21,538] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:12:21,538] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:12:21,550] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:12:21,555] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221112T000000, start_date=20230206T021221, end_date=20230206T021221
[2023-02-05 21:12:21,571] {standard_task_runner.py:92} ERROR - Failed to execute job 155 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35103)
[2023-02-05 21:12:21,598] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:12:21,645] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:15:38,178] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2023-02-05 21:15:38,218] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2023-02-05 21:15:38,219] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:15:38,219] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:15:38,219] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:15:38,260] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-12 00:00:00+00:00
[2023-02-05 21:15:38,265] {standard_task_runner.py:52} INFO - Started process 35321 to run task
[2023-02-05 21:15:38,273] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-12T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmpc__diw_d', '--error-file', '/tmp/tmp8322tuaz']
[2023-02-05 21:15:38,274] {standard_task_runner.py:80} INFO - Job 148: Subtask task_2
[2023-02-05 21:15:38,377] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:15:38,690] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-12T00:00:00+00:00
[2023-02-05 21:15:38,691] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:15:38,692] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:15:38,700] {subprocess.py:85} INFO - Output:
[2023-02-05 21:15:38,702] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:15:38,702] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:15:38,702] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:15:38,713] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:15:38,718] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221112T000000, start_date=20230206T021538, end_date=20230206T021538
[2023-02-05 21:15:38,736] {standard_task_runner.py:92} ERROR - Failed to execute job 148 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35321)
[2023-02-05 21:15:38,766] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:15:38,811] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:34:41,803] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2023-02-05 21:34:41,817] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2023-02-05 21:34:41,817] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:34:41,818] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:34:41,818] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:34:41,838] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-12 00:00:00+00:00
[2023-02-05 21:34:41,842] {standard_task_runner.py:52} INFO - Started process 36185 to run task
[2023-02-05 21:34:41,847] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-12T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmp50c894dq', '--error-file', '/tmp/tmp9tytrvxk']
[2023-02-05 21:34:41,848] {standard_task_runner.py:80} INFO - Job 148: Subtask task_2
[2023-02-05 21:34:41,931] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-12T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:34:42,027] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-12T00:00:00+00:00
[2023-02-05 21:34:42,028] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:34:42,029] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:34:42,041] {subprocess.py:85} INFO - Output:
[2023-02-05 21:34:42,043] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:34:42,043] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:34:42,044] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:34:42,067] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:34:42,074] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221112T000000, start_date=20230206T023441, end_date=20230206T023442
[2023-02-05 21:34:42,150] {standard_task_runner.py:92} ERROR - Failed to execute job 148 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 36185)
[2023-02-05 21:34:42,183] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:34:42,232] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
