[2023-02-05 21:18:03,939] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2023-02-05 21:18:03,950] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2023-02-05 21:18:03,950] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:18:03,950] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:18:03,950] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:18:03,972] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-29 00:00:00+00:00
[2023-02-05 21:18:03,977] {standard_task_runner.py:52} INFO - Started process 35485 to run task
[2023-02-05 21:18:03,983] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-29T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmpgs3cg682', '--error-file', '/tmp/tmpvblsfyxb']
[2023-02-05 21:18:03,984] {standard_task_runner.py:80} INFO - Job 182: Subtask task_2
[2023-02-05 21:18:04,096] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-29T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:18:04,203] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T00:00:00+00:00
[2023-02-05 21:18:04,204] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:18:04,205] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:18:04,214] {subprocess.py:85} INFO - Output:
[2023-02-05 21:18:04,215] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:18:04,216] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:18:04,216] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:18:04,229] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:18:04,234] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221129T000000, start_date=20230206T021803, end_date=20230206T021804
[2023-02-05 21:18:04,253] {standard_task_runner.py:92} ERROR - Failed to execute job 182 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35485)
[2023-02-05 21:18:04,274] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:18:04,337] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
