[2023-02-05 21:10:58,429] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2023-02-05 21:10:58,439] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2023-02-05 21:10:58,439] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:10:58,439] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:10:58,440] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:10:58,458] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-02 00:00:00+00:00
[2023-02-05 21:10:58,461] {standard_task_runner.py:52} INFO - Started process 34996 to run task
[2023-02-05 21:10:58,466] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmp0wjp527y', '--error-file', '/tmp/tmpb37obck3']
[2023-02-05 21:10:58,468] {standard_task_runner.py:80} INFO - Job 130: Subtask task_2
[2023-02-05 21:10:58,543] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:10:58,623] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2023-02-05 21:10:58,625] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:10:58,625] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:10:58,633] {subprocess.py:85} INFO - Output:
[2023-02-05 21:10:58,634] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:10:58,634] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:10:58,634] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:10:58,646] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:10:58,650] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221102T000000, start_date=20230206T021058, end_date=20230206T021058
[2023-02-05 21:10:58,665] {standard_task_runner.py:92} ERROR - Failed to execute job 130 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 34996)
[2023-02-05 21:10:58,677] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:10:58,720] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:14:02,313] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2023-02-05 21:14:02,324] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2023-02-05 21:14:02,324] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:14:02,324] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:14:02,324] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:14:02,346] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-02 00:00:00+00:00
[2023-02-05 21:14:02,349] {standard_task_runner.py:52} INFO - Started process 35213 to run task
[2023-02-05 21:14:02,355] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmp8vjxmr8g', '--error-file', '/tmp/tmp9z143zwu']
[2023-02-05 21:14:02,356] {standard_task_runner.py:80} INFO - Job 128: Subtask task_2
[2023-02-05 21:14:02,436] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:14:02,532] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2023-02-05 21:14:02,533] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:14:02,534] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:14:02,545] {subprocess.py:85} INFO - Output:
[2023-02-05 21:14:02,547] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:14:02,547] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:14:02,548] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:14:02,559] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:14:02,563] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221102T000000, start_date=20230206T021402, end_date=20230206T021402
[2023-02-05 21:14:02,586] {standard_task_runner.py:92} ERROR - Failed to execute job 128 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35213)
[2023-02-05 21:14:02,606] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:14:02,703] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:33:07,300] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2023-02-05 21:33:07,310] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2023-02-05 21:33:07,310] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:33:07,310] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:33:07,311] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:33:07,332] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-02 00:00:00+00:00
[2023-02-05 21:33:07,335] {standard_task_runner.py:52} INFO - Started process 36075 to run task
[2023-02-05 21:33:07,340] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmpbbuea5lr', '--error-file', '/tmp/tmp7mae8c40']
[2023-02-05 21:33:07,342] {standard_task_runner.py:80} INFO - Job 128: Subtask task_2
[2023-02-05 21:33:07,451] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-02T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:33:07,537] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2023-02-05 21:33:07,538] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:33:07,539] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:33:07,547] {subprocess.py:85} INFO - Output:
[2023-02-05 21:33:07,548] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:33:07,548] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:33:07,548] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:33:07,560] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:33:07,563] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221102T000000, start_date=20230206T023307, end_date=20230206T023307
[2023-02-05 21:33:07,579] {standard_task_runner.py:92} ERROR - Failed to execute job 128 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 36075)
[2023-02-05 21:33:07,592] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:33:07,638] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
