[2023-02-05 21:17:54,586] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-28T00:00:00+00:00 [queued]>
[2023-02-05 21:17:54,597] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-28T00:00:00+00:00 [queued]>
[2023-02-05 21:17:54,597] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:17:54,597] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:17:54,597] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:17:54,618] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-28 00:00:00+00:00
[2023-02-05 21:17:54,621] {standard_task_runner.py:52} INFO - Started process 35477 to run task
[2023-02-05 21:17:54,627] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-28T00:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmpbmkopz6l', '--error-file', '/tmp/tmp6_8an5ze']
[2023-02-05 21:17:54,628] {standard_task_runner.py:80} INFO - Job 180: Subtask task_2
[2023-02-05 21:17:54,710] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-28T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:17:54,816] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T00:00:00+00:00
[2023-02-05 21:17:54,817] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:17:54,818] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:17:54,825] {subprocess.py:85} INFO - Output:
[2023-02-05 21:17:54,828] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:17:54,829] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:17:54,829] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:17:54,842] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:17:54,849] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221128T000000, start_date=20230206T021754, end_date=20230206T021754
[2023-02-05 21:17:54,894] {standard_task_runner.py:92} ERROR - Failed to execute job 180 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35477)
[2023-02-05 21:17:54,927] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:17:54,995] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
