[2023-02-05 23:41:21,770] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring_trigger_rules.task_2 scheduled__2022-11-15T00:00:00+00:00 [queued]>
[2023-02-05 23:41:21,781] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring_trigger_rules.task_2 scheduled__2022-11-15T00:00:00+00:00 [queued]>
[2023-02-05 23:41:21,781] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 23:41:21,781] {taskinstance.py:1377} INFO - Starting attempt 2 of 3
[2023-02-05 23:41:21,781] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 23:41:21,801] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-15 00:00:00+00:00
[2023-02-05 23:41:21,804] {standard_task_runner.py:52} INFO - Started process 39668 to run task
[2023-02-05 23:41:21,809] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring_trigger_rules', 'task_2', 'scheduled__2022-11-15T00:00:00+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/06.2_monitoring_trigger_rules.py', '--cfg-path', '/tmp/tmp0i3lghn9', '--error-file', '/tmp/tmpr2g43k4a']
[2023-02-05 23:41:21,810] {standard_task_runner.py:80} INFO - Job 365: Subtask task_2
[2023-02-05 23:41:21,884] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring_trigger_rules.task_2 scheduled__2022-11-15T00:00:00+00:00 [running]> on host pc.
[2023-02-05 23:41:21,960] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring_trigger_rules
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-15T00:00:00+00:00
[2023-02-05 23:41:21,962] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 23:41:21,963] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 23:41:21,970] {subprocess.py:85} INFO - Output:
[2023-02-05 23:41:21,971] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 23:41:21,972] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 23:41:21,972] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 23:41:21,983] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 23:41:21,987] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=06_monitoring_trigger_rules, task_id=task_2, execution_date=20221115T000000, start_date=20230206T044121, end_date=20230206T044121
[2023-02-05 23:41:22,008] {standard_task_runner.py:92} ERROR - Failed to execute job 365 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 39668)
[2023-02-05 23:41:22,020] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 23:41:22,062] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
