[2023-02-05 21:12:28,213] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2023-02-05 21:12:28,223] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2023-02-05 21:12:28,223] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:12:28,223] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:12:28,223] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:12:28,242] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-13 00:00:00+00:00
[2023-02-05 21:12:28,246] {standard_task_runner.py:52} INFO - Started process 35114 to run task
[2023-02-05 21:12:28,251] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-13T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmpu0wltgfa', '--error-file', '/tmp/tmpe3uqqt1r']
[2023-02-05 21:12:28,252] {standard_task_runner.py:80} INFO - Job 157: Subtask task_2
[2023-02-05 21:12:28,341] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:12:28,569] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-13T00:00:00+00:00
[2023-02-05 21:12:28,572] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:12:28,573] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:12:28,581] {subprocess.py:85} INFO - Output:
[2023-02-05 21:12:28,582] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:12:28,583] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:12:28,583] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:12:28,597] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:12:28,603] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221113T000000, start_date=20230206T021228, end_date=20230206T021228
[2023-02-05 21:12:28,638] {standard_task_runner.py:92} ERROR - Failed to execute job 157 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35114)
[2023-02-05 21:12:28,663] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:12:28,749] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:15:45,265] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2023-02-05 21:15:45,275] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2023-02-05 21:15:45,275] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:15:45,275] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:15:45,275] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:15:45,296] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-13 00:00:00+00:00
[2023-02-05 21:15:45,300] {standard_task_runner.py:52} INFO - Started process 35329 to run task
[2023-02-05 21:15:45,305] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-13T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmp_2ti1c7l', '--error-file', '/tmp/tmpg2o3g69c']
[2023-02-05 21:15:45,306] {standard_task_runner.py:80} INFO - Job 150: Subtask task_2
[2023-02-05 21:15:45,381] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:15:45,463] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-13T00:00:00+00:00
[2023-02-05 21:15:45,464] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:15:45,465] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:15:45,474] {subprocess.py:85} INFO - Output:
[2023-02-05 21:15:45,475] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:15:45,475] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:15:45,476] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:15:45,487] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:15:45,491] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221113T000000, start_date=20230206T021545, end_date=20230206T021545
[2023-02-05 21:15:45,508] {standard_task_runner.py:92} ERROR - Failed to execute job 150 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 35329)
[2023-02-05 21:15:45,516] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:15:45,560] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-05 21:34:48,790] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2023-02-05 21:34:48,805] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2023-02-05 21:34:48,805] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:34:48,805] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-05 21:34:48,805] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 21:34:48,875] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-13 00:00:00+00:00
[2023-02-05 21:34:48,878] {standard_task_runner.py:52} INFO - Started process 36193 to run task
[2023-02-05 21:34:48,884] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring', 'task_2', 'scheduled__2022-11-13T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/06_monitoring.py', '--cfg-path', '/tmp/tmp5jajmhax', '--error-file', '/tmp/tmpii42vow9']
[2023-02-05 21:34:48,885] {standard_task_runner.py:80} INFO - Job 150: Subtask task_2
[2023-02-05 21:34:48,979] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring.task_2 scheduled__2022-11-13T00:00:00+00:00 [running]> on host pc.
[2023-02-05 21:34:49,075] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-13T00:00:00+00:00
[2023-02-05 21:34:49,076] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 21:34:49,077] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 21:34:49,086] {subprocess.py:85} INFO - Output:
[2023-02-05 21:34:49,087] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 21:34:49,087] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 21:34:49,088] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 21:34:49,100] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 21:34:49,109] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=06_monitoring, task_id=task_2, execution_date=20221113T000000, start_date=20230206T023448, end_date=20230206T023449
[2023-02-05 21:34:49,133] {standard_task_runner.py:92} ERROR - Failed to execute job 150 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 36193)
[2023-02-05 21:34:49,139] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 21:34:49,193] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
