[2023-02-07 22:47:49,088] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 09_Xcoms.task_1_source scheduled__2022-12-04T00:00:00+00:00 [queued]>
[2023-02-07 22:47:49,098] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 09_Xcoms.task_1_source scheduled__2022-12-04T00:00:00+00:00 [queued]>
[2023-02-07 22:47:49,098] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-07 22:47:49,098] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-07 22:47:49,098] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-07 22:47:49,121] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_1_source> on 2022-12-04 00:00:00+00:00
[2023-02-07 22:47:49,124] {standard_task_runner.py:52} INFO - Started process 48736 to run task
[2023-02-07 22:47:49,130] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '09_Xcoms', 'task_1_source', 'scheduled__2022-12-04T00:00:00+00:00', '--job-id', '1033', '--raw', '--subdir', 'DAGS_FOLDER/09_xcoms.py', '--cfg-path', '/tmp/tmpsvi5160r', '--error-file', '/tmp/tmpoxcv754h']
[2023-02-07 22:47:49,132] {standard_task_runner.py:80} INFO - Job 1033: Subtask task_1_source
[2023-02-07 22:47:49,214] {task_command.py:371} INFO - Running <TaskInstance: 09_Xcoms.task_1_source scheduled__2022-12-04T00:00:00+00:00 [running]> on host pc.
[2023-02-07 22:47:49,309] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=09_Xcoms
AIRFLOW_CTX_TASK_ID=task_1_source
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-04T00:00:00+00:00
[2023-02-07 22:47:49,311] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-07 22:47:49,312] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sleep 5 && $((5 * 3))']
[2023-02-07 22:47:49,321] {subprocess.py:85} INFO - Output:
[2023-02-07 22:47:54,490] {subprocess.py:92} INFO - bash: line 1: 15: command not found
[2023-02-07 22:47:54,491] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-07 22:47:54,504] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-07 22:47:54,508] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=09_Xcoms, task_id=task_1_source, execution_date=20221204T000000, start_date=20230208T034749, end_date=20230208T034754
[2023-02-07 22:47:54,525] {standard_task_runner.py:92} ERROR - Failed to execute job 1033 for task task_1_source (Bash command failed. The command returned a non-zero exit code 127.; 48736)
[2023-02-07 22:47:54,562] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-07 22:47:54,607] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
