[2023-02-07 18:15:02,860] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 07.2_external_task_sensor.waiting_dag scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2023-02-07 18:15:02,871] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 07.2_external_task_sensor.waiting_dag scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2023-02-07 18:15:02,871] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-07 18:15:02,871] {taskinstance.py:1377} INFO - Starting attempt 2 of 1
[2023-02-07 18:15:02,872] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-07 18:15:02,896] {taskinstance.py:1397} INFO - Executing <Task(ExternalTaskSensor): waiting_dag> on 2022-11-01 00:00:00+00:00
[2023-02-07 18:15:02,900] {standard_task_runner.py:52} INFO - Started process 30164 to run task
[2023-02-07 18:15:02,908] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '07.2_external_task_sensor', 'waiting_dag', 'scheduled__2022-11-01T00:00:00+00:00', '--job-id', '422', '--raw', '--subdir', 'DAGS_FOLDER/07.2_external_task_sensor.py', '--cfg-path', '/tmp/tmp3funej_s', '--error-file', '/tmp/tmpf2kw0t87']
[2023-02-07 18:15:02,909] {standard_task_runner.py:80} INFO - Job 422: Subtask waiting_dag
[2023-02-07 18:15:02,990] {task_command.py:371} INFO - Running <TaskInstance: 07.2_external_task_sensor.waiting_dag scheduled__2022-11-01T00:00:00+00:00 [running]> on host pc.
[2023-02-07 18:15:03,084] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=07.2_external_task_sensor
AIRFLOW_CTX_TASK_ID=waiting_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T00:00:00+00:00
[2023-02-07 18:15:03,085] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:15:13,103] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:15:23,112] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:15:33,124] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:15:43,140] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:15:53,152] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:16:03,164] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:16:13,174] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:16:23,189] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:16:33,202] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:16:43,217] {external_task.py:184} INFO - Poking for tasks ['task_1'] in dag 07_external_task_sensor on 2022-11-01T00:00:00+00:00 ... 
[2023-02-07 18:16:49,001] {local_task_job.py:220} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-02-07 18:16:49,005] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 30164. PIDs of all processes in the group: [30164]
[2023-02-07 18:16:49,005] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 30164
[2023-02-07 18:16:49,005] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-02-07 18:16:49,025] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/sensors/base.py", line 299, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1563, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-02-07 18:16:49,039] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=07.2_external_task_sensor, task_id=waiting_dag, execution_date=20221101T000000, start_date=20230207T231502, end_date=20230207T231649
[2023-02-07 18:16:49,105] {standard_task_runner.py:92} ERROR - Failed to execute job 422 for task waiting_dag (Task received SIGTERM signal; 30164)
[2023-02-07 18:16:49,116] {process_utils.py:75} INFO - Process psutil.Process(pid=30164, status='terminated', exitcode=1, started='18:15:01') (30164) terminated with exit code 1
