[2023-02-05 23:38:04,360] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring_trigger_rules.task_2 scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2023-02-05 23:38:04,372] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 06_monitoring_trigger_rules.task_2 scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2023-02-05 23:38:04,373] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 23:38:04,373] {taskinstance.py:1377} INFO - Starting attempt 2 of 3
[2023-02-05 23:38:04,373] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 23:38:04,399] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_2> on 2022-11-08 00:00:00+00:00
[2023-02-05 23:38:04,402] {standard_task_runner.py:52} INFO - Started process 39404 to run task
[2023-02-05 23:38:04,414] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '06_monitoring_trigger_rules', 'task_2', 'scheduled__2022-11-08T00:00:00+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/06.2_monitoring_trigger_rules.py', '--cfg-path', '/tmp/tmp87cfn621', '--error-file', '/tmp/tmpm7zy6ieu']
[2023-02-05 23:38:04,415] {standard_task_runner.py:80} INFO - Job 309: Subtask task_2
[2023-02-05 23:38:04,504] {task_command.py:371} INFO - Running <TaskInstance: 06_monitoring_trigger_rules.task_2 scheduled__2022-11-08T00:00:00+00:00 [running]> on host pc.
[2023-02-05 23:38:04,586] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=06_monitoring_trigger_rules
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-08T00:00:00+00:00
[2023-02-05 23:38:04,588] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 23:38:04,588] {subprocess.py:74} INFO - Running command: ['bash', '-c', "sleep 2 && echo 'Second task!"]
[2023-02-05 23:38:04,595] {subprocess.py:85} INFO - Output:
[2023-02-05 23:38:04,597] {subprocess.py:92} INFO - bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-02-05 23:38:04,597] {subprocess.py:92} INFO - bash: -c: line 2: syntax error: unexpected end of file
[2023-02-05 23:38:04,597] {subprocess.py:96} INFO - Command exited with return code 2
[2023-02-05 23:38:04,609] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/milo/13-airflow/airflowhome/airflowenv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-05 23:38:04,613] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=06_monitoring_trigger_rules, task_id=task_2, execution_date=20221108T000000, start_date=20230206T043804, end_date=20230206T043804
[2023-02-05 23:38:04,632] {standard_task_runner.py:92} ERROR - Failed to execute job 309 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 39404)
[2023-02-05 23:38:04,658] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-05 23:38:04,703] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
